SportsStore/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace SportsStore.Controllers
{
    public class OrdersController : Controller
    {
        private IRepository productRepository;
        private IOrdersRepository ordersReporitory;

        public OrdersController(IRepository productRepo, IOrdersRepository ordersRepo)
        {
            this.productRepository = productRepo;
            this.ordersReporitory = ordersRepo;
        }

        public IActionResult Index() => View(ordersReporitory.Orders);

        public IActionResult EditOrder(long id)
        {
            var products = productRepository.Products;

            Order order = id == 0 ? new Order() : ordersReporitory.GetOrder(id);
            
            IDictionary<long, OrderLine> linesMap = order.Lines?.ToDictionary(l => l.ProductId)
                ?? new Dictionary<long, OrderLine>();
            
            ViewBag.Lines = products.Select(p => linesMap.ContainsKey(p.Id)
                ? linesMap[p.Id]
                : new OrderLine { Product = p, ProductId = p.Id, Quantity = 0 });
            
            return View(order);
        }

        [HttpPost]
        public IActionResult AddOrUpdateOrder(Order order)
        {
            order.Lines = order.Lines.Where(l => l.Id > 0 || (l.Id == 0 && l.Quantity > 0)).ToArray();
            if(order.Id == 0)
            {
                ordersReporitory.AddOrder(order);
            } else
            {
                ordersReporitory.UpdateOrder(order);
            }


            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DeleteOrder(Order order)
        {
            ordersReporitory.DeleteOrder(order);
            return RedirectToAction(nameof(Index));
        }
    }
}

SportsStore/Controllers/SeedController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportsStore.Models;
using System.Linq;

namespace SportsStore.Controllers
{
    public class SeedController : Controller
    {
        private DataContext context;

        public SeedController(DataContext ctx) => context = ctx;

        public IActionResult Index()
        {
            ViewBag.Count = context.Products.Count();
                
            return View(context.Products.Include(p => p.Category).OrderBy(p => p.Id).Take(20));
        }

        [HttpPost]
        [System.Obsolete]
        public IActionResult CreateSeedData(int count)
        {
            ClearData();
            if(count > 0)
            {
                context.Database.SetCommandTimeout(System.TimeSpan.FromMinutes(10));
                context.Database.ExecuteSqlCommand("DROP PROCEDURE IF EXISTS CreateSeedData");
                context.Database.ExecuteSqlCommand($@"
CREATE PROCEDURE CreateSeedData
@RowCount decimal
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @i INT = 1;
	DECLARE @catId BIGINT;
	DECLARE @CatCount INT = @RowCount / 10;
	DECLARE @pprice DECIMAL(5,2);
	DECLARE @rprice DECIMAL(5,2);
	BEGIN TRANSACTION
		WHILE @i <= @CatCount
			BEGIN
				INSERT INTO Categories (Name, Description)
				VALUES (CONCAT('Category-', @i),'Test Data Category');
				SET @catid = SCOPE_IDENTITY();
				DECLARE @j INT = 1;
				WHILE @j <= 10
					BEGIN
						SET @pprice = RAND() * (500-5+1);
						SET @rprice = (RAND () * @pprice) + @pprice;

						INSERT INTO Products (Name, Categoryid, PurchasePrice, RetailPrice)
						VALUES (CONCAT('Product', @i, '-', @j),@catId, @pprice, @rprice)
						SET @j = @j + 1
					END
				SET @i = @i + 1
			END
		COMMIT
END
");
                context.Database.BeginTransaction();
                context.Database.ExecuteSqlCommand($"EXEC CreateSeedData @RowCount = {count}");
                context.Database.CommitTransaction();
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [System.Obsolete]
        public IActionResult ClearData()
        {
            context.Database.SetCommandTimeout(System.TimeSpan.FromMinutes(10));
            context.Database.BeginTransaction();
            context.Database.ExecuteSqlCommand("DELETE FROM Orders");
            context.Database.ExecuteSqlCommand("DELETE FROM Categories");
            context.Database.CommitTransaction();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult CreateProductionData()
        {
            ClearData();
            context.Categories.AddRange(new Category[]
            {
                new Category
                {
                    Name = "Watersports",
                    Description = "Make a splash",
                    Products = new Product[]
                    {
                        new Product
                        {
                            Name = "Kayak",
                            Description = "A boat for one person",
                            PurchasePrice = 200,
                            RetailPrice = 275
                        },
                        new Product
                        {
                            Name = "Lifejacket",
                            Description = "Protective and fashionable",
                            PurchasePrice = 40,
                            RetailPrice = 48.95m
                        }
                    }
                },
                new Category
                {
                    Name = "Soccer",
                    Description = "The world's favorite game",
                    Products = new Product[]
                    {
                        new Product
                        {
                            Name = "Soccer ball",
                            Description = "FIFA-approved size and weight",
                            PurchasePrice = 18,
                            RetailPrice = 19.50m
                        },
                        new Product
                        {
                            Name = "Corner Flags",
                            Description = "Give your playing field a professional touch",
                            PurchasePrice = 32.50m,
                            RetailPrice = 34.95m
                        },
                        new Product
                        {
                            Name = "Stadium",
                            Description = "Flat-packet 35000-seat stadium",
                            PurchasePrice = 75000,
                            RetailPrice = 79500
                        }
                    }
                },
                new Category
                {
                    Name = "Chess",
                    Description = "The thinky game",
                    Products = new Product[]
                    {
                        new Product
                        {
                            Name = "Thinkin cap",
                            Description = "Improve brain efficiency by 75%",
                            PurchasePrice = 10,
                            RetailPrice = 16
                        },
                        new Product
                        {
                            Name = "Unsteady chair",
                            Description = "Secretely give your opponent a disadvantage",
                            PurchasePrice = 28,
                            RetailPrice = 29.95m
                        },
                        new Product
                        {
                            Name = "Human chess board",
                            Description = "A fun game for the family",
                            PurchasePrice = 68.50m,
                            RetailPrice = 75
                        },
                        new Product
                        {
                            Name = "Bling-Bling king",
                            Description = "Gold plated, giamond-studded King",
                            PurchasePrice = 800,
                            RetailPrice = 1200
                        }
                    }
                }
            });
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

SportsStore/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.Pages;

namespace SportsStore.Controllers
{
    public class StoreController : Controller
    {
        private IRepository productRepository;
        private ICategoryRepository categoryRepository;

        public StoreController(IRepository repo, ICategoryRepository catRepo)
        {
            productRepository = repo;
            categoryRepository = catRepo;
        }
        
        public IActionResult Index([FromQuery(Name = "options")] 
            QueryOptions productOptions, 
            QueryOptions catOptions, 
            long category)
        {
            ViewBag.Categories = categoryRepository.GetCategories(catOptions);
            ViewBag.SelectedCategory = category;

            return View(productRepository.GetProducts(productOptions, category));
        }
    }
}

SportsStore/Views/Shared/PageOptions.cshtml
<div class="container-fluid mt-2">
    <div class="row m-1">
        <div class="col"></div>
        <div class="col-1">
            <label class="col-form-label">Search</label>
        </div>
        <div class="col-3">
            <select form="pageForm" name="options.searchpropertyname" class="form-control">
                @foreach(string s in ViewBag.searches as string[]){
                    <option value="@s" selected="@(Model.Options.SearchPropertyName == s)"> 
                        @(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))
                    </option>
                }
            </select>
        </div>        
        <div class="col">
            <input form="pageForm" class="form-control" name="options.searchterm" value="@Model.Options.SearchTerm" />
        </div>

        <div class="col-1 text-right">
            <button form="pageForm" class="btn btn-secondary" type="submit">
                Search
            </button>
        </div>
        <div class="col"></div>
    </div>

    <div class="row m-1">
        <div class="col"></div>
        <div class="col-1">
            <label class="col-form-label">Sort</label>
        </div>
        <div class="col-3">
            <select form="pageForm" name="options.OrderPropertyName" class="form-control">
                @foreach(string s in ViewBag.sorts as string[]){
                    <option value="@s" selected="@Model.Options.OrderPropertyName == s">
                        @(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))
                    </option>
                }
            </select>
        </div>
        <div class="col form-check form-check-inline">
            <input form="pageForm" type="checkbox" name="Options.DescendingOrder" 
            id="Options.descendingOrder"
            class="form-check-input" value="true"
            checked="@Model.Options.DescendingOrder"/>
            <label class="form-check-label">Descending Order</label>
        </div>
        <div class="col-1 text-right">
            <button form="pageForm" class="btn btn-secondary" type="submit">
                Sort
            </button>
        </div>
        <div class="col"></div>
    </div>
</div>

SportsStore/Views/Shared/Pages.cshtml
@using SportsStore.Models.Pages

@model PagedList<Product>

<form id="pageForm" method="get" class="form-inline d-inline-block"> 
    <!--Previous page button-->
    <button name="options.currentPage" value="@(Model.CurrentPage - 1)" 
        class="btn btn-outline-primary" @(!Model.HasPreviousPage ? "disabled" : "") type="submit">
        Previous
    </button>
    
    <!--First three pages-->
    @for(int i=1; i<=3 && i < Model.TotalPages; i++ ){
        <button name="options.currentPage" value="@i" type="submit" 
            class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">
            @i
        </button>
    }
    <!--Current page-->
    @if(Model.CurrentPage > 3 && Model.TotalPages - Model.CurrentPage >= 3) {
        @:...
        <button class="btn btn-outline-primary active">@Model.CurrentPage</button>
    }
    
    <!--Last three pages-->
    @if(Model.TotalPages > 3){
        @:...
        @for(int i = Math.Max(4, Model.TotalPages - 2 ); i <= Model.TotalPages; i++){
            <button name="options.currentPage" value="@i" type="submit" 
                class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">
                @i
            </button>
        }
    }
    <!--Next page button -->
    <button name="options.currentPage" value="@(Model.CurrentPage + 1)" type="submit" 
        class="btn btn-outline-primary" 
        @(!Model.HasNextPage ? "disabled" : "")>
        Next
    </button>

    <select name="options.pageSize" class="form-control ml-1 mr-1">
        @foreach(int val in new[] { 10, 25, 50, 100}){
            <option value="@val" selected="@(Model.PageSize == val)">
                @val
            </option>
        }
    </select>

    <input type="hidden" name="options.currentPage" value="1" />
    <button type="submit" class="btn btn-secondary">Change Page Size</button>
</form>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>SportsStore</title>
        
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

        <style>
            .placeholder {visibility:hidden; display:none}
            .placeholder:only-child {visibility:visible; display:flex}
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row p-2">
                <div class="col-2">
                    <a asp-controller="Home" asp-action="Index" class="@GetClassForButton("Home")">Products</a>
                    <a asp-controller="Categories" asp-action="Index" class="@GetClassForButton("Categories")">Categories</a>
                    <a asp-controller="Orders" asp-action="Index" class="@GetClassForButton("Orders")">Orders</a>
                    <a asp-controller="Seed" asp-action="Index" class="@GetClassForButton("Seed")">Seed data</a>
                    <a asp-controller="Store" asp-action="Index" class="@GetClassForButton("Store")">Store</a>
                </div>
                <div class="col">
                    @RenderBody()
                </div>
            </div>
        </div>
    </body>
</html>

@functions {
    string GetClassForButton(string controller){
        return "btn btn-block " + (ViewContext.RouteData.Values["controller"] as string == controller ? "btn-primary" : "btn-outline-primary");
    }
}